# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-06 15:06
from __future__ import unicode_literals

import deafndumb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deafndumb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=deafndumb.models.get_audio_path),
        ),
        migrations.AlterField(
            model_name='word',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
